name: Build Go Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']
        platform: [amd64, 386, arm64, arm]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build for Linux ${{ matrix.platform }}
      run: |
        GOOS=linux GOARCH=${{ matrix.platform }} go build -o build/tglotterybot_linux_${{ matrix.platform }} .

    - name: Upload Linux Binaries
      uses: actions/upload-artifact@v3
      with:
        name: linux-binaries-${{ matrix.platform }}
        path: build/

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: ['1.20']
        platform: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build for macOS ${{ matrix.platform }}
      run: |
        GOOS=darwin GOARCH=${{ matrix.platform }} go build -o build/tglotterybot_macos_${{ matrix.platform }} .

    - name: Upload macOS Binaries
      uses: actions/upload-artifact@v3
      with:
        name: macos-binaries-${{ matrix.platform }}
        path: build/

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        go-version: ['1.20']
        platform: [amd64, 386]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build for Windows ${{ matrix.platform }}
      run: |
        GOOS=windows GOARCH=${{ matrix.platform }} go build -o build/tglotterybot_windows_${{ matrix.platform }}.exe .

    - name: Upload Windows Binaries
      uses: actions/upload-artifact@v3
      with:
        name: windows-binaries-${{ matrix.platform }}
        path: build/

